-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.3.22-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5958
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table slim_project.movie
CREATE TABLE IF NOT EXISTS `movie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pub_date` datetime DEFAULT NULL,
  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table slim_project.movie: ~10 rows (approximately)
/*!40000 ALTER TABLE `movie` DISABLE KEYS */;
INSERT INTO `movie` (`id`, `title`, `link`, `description`, `pub_date`, `image`) VALUES
	(1, 'John Lewis: Good Trouble - Trailer', 'https://trailers.apple.com/trailers/magnolia/john-lewis-good-trouble', 'Using interviews and rare archival footage, JOHN LEWIS: GOOD TROUBLE chronicles Lewis\' 60-plus years of social activism and legislative action on civil rights, voting rights, gun control, health-care reform and immigration. Using present-day interviews with Lewis, now 80 years old, Porter explores his childhood experiences, his inspiring family and his fateful meeting with Dr. Martin Luther King Jr. in 1957. In addition to her interviews with Lewis and his family, Porter\'s primarily cinéma verité film also includes interviews with political leaders, Congressional colleagues, and other people who figure prominently in his life.', '2020-05-11 00:00:00', 'https://trailers.apple.com/trailers/magnolia/john-lewis-good-trouble/images/poster.jpg'),
	(2, 'Shirley - Trailer', 'https://trailers.apple.com/trailers/independent/shirley', 'Renowned horror writer Shirley Jackson is on the precipice of writing her masterpiece when the arrival of newlyweds upends her meticulous routine and heightens tensions in her already tempestuous relationship with her philandering husband. The middle-aged couple, prone to ruthless barbs and copious afternoon cocktails, begins to toy mercilessly with the naïve young couple at their door.', '2020-05-08 00:00:00', 'https://trailers.apple.com/trailers/independent/shirley/images/poster.jpg'),
	(3, 'Hope Gap - Clip - This Woman', 'https://trailers.apple.com/trailers/roadsideattractions/hope-gap', 'The intimate, intense and loving story of HOPE GAP charts the life of Grace (Annette Bening), shocked to learn her husband (Bill Nighy) is leaving her for another after 29 years of marriage, and the ensuing emotional fallout the dissolution has on their only grown son (Josh O’Connor). Unraveled and feeling displaced in her small seaside town, Grace ultimately regains her footing and discovers a new, powerful voice.', '2020-05-07 00:00:00', 'https://trailers.apple.com/trailers/roadsideattractions/hope-gap/images/poster.jpg'),
	(4, 'Walkaway Joe - Clip - I Know Where You Can Get The Money', 'https://trailers.apple.com/trailers/independent/walkaway-joe', 'WALKAWAY JOE is the story of an unlikely friendship between a young boy searching for his father in pool halls across the country, and a wandering loner hiding from his past. In each other they experience the power of a second chance, and a shot at redemption.', '2020-05-07 00:00:00', 'https://trailers.apple.com/trailers/independent/walkaway-joe/images/poster.jpg'),
	(5, 'Spaceship Earth - Trailer 2', 'https://trailers.apple.com/trailers/independent/spaceship-earth', 'Spaceship Earth is the true, stranger-than-fiction, adventure of eight visionaries who in 1991 spent two years quarantined inside of a self-engineered replica of Earth’s ecosystem called BIOSPHERE 2. The experiment was a worldwide phenomenon, chronicling daily existence in the face of life threatening ecological disaster and a growing criticism that it was nothing more than a cult. The bizarre story is both a cautionary tale and a hopeful lesson of how a small group of dreamers can potentially reimagine a new world.', '2020-05-06 00:00:00', 'https://trailers.apple.com/trailers/independent/spaceship-earth/images/poster.jpg'),
	(6, 'A Good Woman Is Hard To Find - Trailer', 'https://trailers.apple.com/trailers/independent/a-good-woman-is-hard-to-find', 'Set in the underbelly of Northern Ireland, A Good Woman is Hard to Find follows Sarah Collins (Sarah Bolger, “Mayans M.C.”, “The Tudors”, Emelie), a single mother struggling to raise two young children while searching for answers about the unsolved murder of her husband. After being coerced into helping a low-level drug dealer stash stolen narcotics, she finds herself the target of local crime boss Leo Miller (Edward Hogg). Forced to take desperate measures to keep her family safe, Sarah turns the tables on her victimizers in one final act of bloody vengeance.', '2020-05-06 00:00:00', 'https://trailers.apple.com/trailers/independent/a-good-woman-is-hard-to-find/images/poster.jpg'),
	(7, 'A Good Woman Is Hard To Find - Clip', 'https://trailers.apple.com/trailers/independent/a-good-woman-is-hard-to-find', 'Set in the underbelly of Northern Ireland, A Good Woman is Hard to Find follows Sarah Collins (Sarah Bolger, “Mayans M.C.”, “The Tudors”, Emelie), a single mother struggling to raise two young children while searching for answers about the unsolved murder of her husband. After being coerced into helping a low-level drug dealer stash stolen narcotics, she finds herself the target of local crime boss Leo Miller (Edward Hogg). Forced to take desperate measures to keep her family safe, Sarah turns the tables on her victimizers in one final act of bloody vengeance.', '2020-05-06 00:00:00', 'https://trailers.apple.com/trailers/independent/a-good-woman-is-hard-to-find/images/poster.jpg'),
	(8, 'Valley Girl - Featurette', 'https://trailers.apple.com/trailers/independent/valley-girl', 'Julie (Jessica Rothe) is the ultimate ‘80s Valley Girl. A creative free spirit; Julie’s time is spent with her best friends shopping at the Galleria mall and making plans for senior prom. That is, until she falls hard for Randy (Joshua Whitehouse), a Sunset Strip punk rocker, who challenges everything the Valley and Julie stand for. Despite push-back from friends and family, Julie must break out of the safety of her world to follow her heart and discover what it really means to be a Valley Girl. Set to a rock ’n roll ‘80s soundtrack produced by legendary Harvey Mason, Jr. with dance numbers by choreographer Mandy Moore, Valley Girl is a musical adaptation of the classic 1983 hit film that changed American teenage life forever.', '2020-05-06 00:00:00', 'https://trailers.apple.com/trailers/independent/valley-girl/images/poster.jpg'),
	(9, 'Capone - Trailer', 'https://trailers.apple.com/trailers/independent/capone', 'Once a ruthless businessman and bootlegger who ruled Chicago with an iron fist, Alfonse Capone was the most infamous and feared gangster of American lore. At the age of 47, following nearly a decade of imprisonment, dementia rots Alfonse’s mind and his past becomes present. Harrowing memories of his violent and brutal origins melt into his waking life. As he spends his final year surrounded by family with the FBI lying in wait, this ailing patriarch struggles to place the memory of the location of millions of dollars he hid away on his property.', '2020-05-05 00:00:00', 'https://trailers.apple.com/trailers/independent/capone/images/poster.jpg'),
	(10, 'Arkansas - Clip - Meeting Her', 'https://trailers.apple.com/trailers/lions_gate/arkansas', 'In Clark Duke’s directorial debut, Kyle (Liam Hemsworth) and Swin (Clark Duke) live by the orders of an Arkansas-based drug kingpin named Frog (Vince Vaughn), whom they’ve never met. Posing as junior park rangers by day, they operate as low-level drug couriers by night under the watchful eye of Frog’s proxies (John Malkovich and Vivica A. Fox).', '2020-05-05 00:00:00', 'https://trailers.apple.com/trailers/lions_gate/arkansas/images/poster.jpg');
/*!40000 ALTER TABLE `movie` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
